I'm dumb and yml syntax is dumb

diff --git a/.github/workflows/renv_testing.yml b/.github/workflows/renv_testing.yml
--- a/.github/workflows/renv_testing.yml
+++ b/.github/workflows/renv_testing.yml
@@ -38,14 +38,14 @@ jobs:
         Rscript -e 'devtools::install()'
 
     - name: Verify config.yml exists
-        run: |
-          if [ -f "./config.yml" ]; then
-            echo "config.yml found"
-          else
-            echo "config.yml NOT found!"
-            exit 1
-          fi
-        shell: bash
+      run: |
+        if [ -f "./config.yml" ]; then
+          echo "config.yml found"
+        else
+          echo "config.yml NOT found!"
+          exit 1
+        fi
+      shell: bash
 
     - name: Run unit tests
       run: |
